# Generated by Django 2.0.6 on 2019-03-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginmodel',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
